name: Github Actions Bazel Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build by bazel
        working-directory: ./cpp-test/src
        run: bazel build --config=clang_config --sandbox_debug --verbose_failures //main:hello-world

      - uses: lhotari/action-upterm@v1
      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
